FROM python:3.11-slim

WORKDIR /app

COPY client/ /app/
COPY .env .env

RUN pip install pip --upgrade
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py", "--server.headless", "true"]