FROM python:3.11-slim

WORKDIR /server

COPY server/ /server/
COPY db/ db/

RUN pip install pip --upgrade
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]